"""Regenerates submission/main.py from src/adaptive_agent/ + src/adaptive_best_config.json.

AST-based flattening: dependency-ordered concatenation, intra-package imports stripped.
adaptive_agent replaced the former robust_agent architecture (and its build_submission.py /
optimize.py / tuning/ support code, since deleted -- robust_agent's tuning schema didn't apply to
this architecture and left dead imports once robust_agent was removed) as this project's live
agent 2026-08-27 (see docs/tests/LOG.md) --
verified via a real 150-trial Optuna search + verify_candidate/verify_holdout gate,
20W-0L-0T / +79k avg margin against the former robust_agent champion, independently reconfirmed
multiple times before promotion.

Note: `constants.py` and `config.py` both define a few same-named constants
(LIQUIDATION_TURNS, TRAVEL_COST, MAX_HANDS, CASH_RESERVE, LAND_OPEN_DAYS, MAX_EXTRA_LAND,
PRIORITY_BONUS) with different values -- safe in the package because every consumer imports
these specifically from `.config`, never `.constants`. MODULE_ORDER below puts config.py AFTER
constants.py so the flattened file's last (winning) definition matches what `from .config import
X` actually resolves to in the real package -- do not reorder this without re-verifying.

Usage:
    python src/build_adaptive_submission.py
"""
import ast
import json
import pprint
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent
AGENT_DIR = HERE / "adaptive_agent"
OUT_PATH = REPO_ROOT / "submission" / "main.py"
OUT_PATH.parent.mkdir(exist_ok=True)

sys.path.insert(0, str(HERE))

# Dependency order -- each file only references names defined in files before it.
# constants -> config (see note above for why config must come second, not first) ->
# state -> market_forecast -> dispatch -> farm_plan -> market -> agent
MODULE_ORDER = [
    "constants.py",
    "config.py",
    "state.py",
    "market_forecast.py",
    "dispatch.py",
    "farm_plan.py",
    "market.py",
    "preempt.py",
    "agent.py",
]


class ImportStripper(ast.NodeTransformer):
    """Strips intra-package (`from .x import y`) imports -- their targets are
    flattened into this same file already. Aliased imports (`from .config
    import get_config as _cfg`) need an assignment left behind (`_cfg =
    get_config`) or the alias name goes undefined once the import itself is
    dropped -- caught by the package-vs-flattened self-play verification
    below (a NameError on first use, not a silent behavior change)."""

    def visit_ImportFrom(self, node):
        if node.level == 0:
            return node
        alias_assigns = [
            ast.Assign(
                targets=[ast.Name(id=a.asname, ctx=ast.Store())],
                value=ast.Name(id=a.name, ctx=ast.Load()),
            )
            for a in node.names
            if a.asname and a.asname != a.name
        ]
        return alias_assigns or None

    def visit_Import(self, node):
        return node


class HoistImports(ast.NodeTransformer):
    def __init__(self):
        self.imports = []

    def visit_Import(self, node):
        self.imports.append(ast.unparse(node))
        return None

    def visit_ImportFrom(self, node):
        if node.level == 0:
            self.imports.append(ast.unparse(node))
        return None


def flatten_module(path):
    tree = ast.parse(path.read_text())
    tree = ImportStripper().visit(tree)
    hoister = HoistImports()
    tree = hoister.visit(tree)
    ast.fix_missing_locations(tree)
    return hoister.imports, ast.unparse(tree)


def build():
    config_path = HERE / "adaptive_best_config.json"
    tuned = json.loads(config_path.read_text()) if config_path.exists() else {}
    config_src = "CONFIG = " + pprint.pformat(tuned, sort_dicts=False, width=100)

    modules_code = []
    all_imports = set()
    for mod_name in MODULE_ORDER:
        imports, code = flatten_module(AGENT_DIR / mod_name)
        all_imports.update(imports)
        modules_code.append(f"# {'-' * 74}\n# {mod_name}\n# {'-' * 74}\n\n{code}")

    all_imports_src = "\n".join(sorted(all_imports))
    modules_src = "\n\n\n".join(modules_code)

    out = f'''"""Kaggriculture competition submission.

Auto-generated by build_adaptive_submission.py from src/adaptive_agent/ +
src/adaptive_best_config.json -- do not hand-edit; regenerate instead.

Single-file on purpose: no sibling-file imports to get wrong on a real
submission.
"""

{all_imports_src}

{config_src}

{modules_src}


# --------------------------------------------------------------------------
# Entry point -- must be the last callable defined in this file.
# --------------------------------------------------------------------------
agent = make_agent(CONFIG)
'''
    OUT_PATH.write_text(out)
    print(f"Wrote {OUT_PATH} ({len(out)} bytes)")


if __name__ == "__main__":
    build()
