"""Regenerates submission/main.py from src/farm_utils.py + src/agent.py
+ src/best_config.json.

Run this whenever any of those three change -- never hand-edit
submission/main.py directly, or it drifts out of sync silently (this is
exactly what the single hand-maintained copy risked before this script
existed).

Usage:
    python src/build_submission.py
"""
import ast
import json
import pprint
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent
OUT_PATH = REPO_ROOT / "submission" / "main.py"

sys.path.insert(0, str(HERE))

FARM_UTILS_FUNCS = ["step_toward", "closest", "act_or_move", "shed_tiles"]
ROBUST_AGENT_FUNCS = [
    "_crop_cycle_days", "_crop_score", "_diversified_crop_score", "_animal_score",
    "_base_price", "_plant_harvest_ready", "_scan_farm", "_plan_units",
    "_carried_total", "_opponent_incoming_supply", "_dynamic_sell_fraction", "_market_orders",
]
# Module-level dicts _plan_units depends on (not `def`s, so _extract_funcs
# below can't see them -- a static call-graph check only walks function
# bodies for Name/Call references, so a missing top-level constant like this
# went undetected once already, see docs/tests/LOG.md's build_submission.py
# entry). Keep in sync by hand if _plan_units grows another one.
ROBUST_AGENT_CONSTANTS = ["STATIC_TASK_ACTIONS", "TASK_INFO_KEY"]


def _extract_funcs(path, names):
    source = path.read_text()
    tree = ast.parse(source)
    segments = {}
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name in names:
            segments[node.name] = ast.get_source_segment(source, node)
    missing = set(names) - set(segments)
    if missing:
        raise RuntimeError(f"{path}: missing expected functions {sorted(missing)}")
    return [segments[n] for n in names]


def _extract_assigns(path, names):
    source = path.read_text()
    tree = ast.parse(source)
    segments = {}
    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            if node.targets[0].id in names:
                segments[node.targets[0].id] = ast.get_source_segment(source, node)
    missing = set(names) - set(segments)
    if missing:
        raise RuntimeError(f"{path}: missing expected top-level assignments {sorted(missing)}")
    return [segments[n] for n in names]


def build():
    from agent import DEFAULT_CONFIG

    best_config_path = HERE / "best_config.json"
    tuned = json.loads(best_config_path.read_text()) if best_config_path.exists() else {}
    config = dict(DEFAULT_CONFIG)
    config.update(tuned)

    farm_utils_src = "\n\n\n".join(_extract_funcs(HERE / "farm_utils.py", FARM_UTILS_FUNCS))
    robust_agent_constants_src = "\n".join(_extract_assigns(HERE / "agent.py", ROBUST_AGENT_CONSTANTS))
    robust_agent_src = "\n\n\n".join(_extract_funcs(HERE / "agent.py", ROBUST_AGENT_FUNCS))
    config_src = "CONFIG = " + pprint.pformat(config, sort_dicts=False, width=100)

    out = f'''"""Kaggriculture competition submission.

Auto-generated by src/build_submission.py from src/farm_utils.py +
src/agent.py + src/best_config.json -- do not hand-edit; regenerate
instead (`python src/build_submission.py`). See docs/tests/LOG.md for how
this config was found and verified.

Single-file on purpose: no sibling-file imports to get wrong on a real
submission with a 5/day limit.

Verified locally before submission:
    python src/run_match.py agent:robust_agent kawa_route_agent:kawa_route_agent
"""

import math
import sys

from kaggle_environments.envs.kaggriculture.kaggriculture import (
    ANIMALS,
    CROPS,
    LAND_PRICES,
    MARKET_PARAMS,
)

{config_src}

SAFE_FALLBACK = {{"farmer": ["PASS"], "hands": [], "market": []}}


# --------------------------------------------------------------------------
# farm_utils.py -- movement/geometry helpers
# --------------------------------------------------------------------------

{farm_utils_src}


# --------------------------------------------------------------------------
# agent.py -- scoring, scanning, task assignment, market orders
# --------------------------------------------------------------------------

{robust_agent_constants_src}


{robust_agent_src}


# --------------------------------------------------------------------------
# Entry point -- must be the last callable defined in this file.
# kaggle_environments loads a file agent by exec'ing it and taking the LAST
# callable bound in the resulting module namespace (see
# kaggle_environments.agent.get_last_callable), not a specifically-named
# function. Do not add any code after the `agent = make_agent()` line below.
# --------------------------------------------------------------------------

def make_agent(config):
    cfg = dict(config)
    state = {{"unit_targets": {{}}}}

    def agent(obs):
        try:
            farms = obs.get("farms", [])
            player = obs.get("player", 0)
            if not farms or player >= len(farms):
                return dict(SAFE_FALLBACK)

            farm = farms[player]
            opponent_farm = next((f for i, f in enumerate(farms) if i != player), None)
            private = obs.get("private", {{}}) or {{}}
            day = obs.get("day", 0)
            board_size = len(farm["tiles"])
            prices = (obs.get("market", {{}}) or {{}}).get("prices", {{}}) or {{}}

            info = _scan_farm(farm, board_size, day)
            opponent_supply = _opponent_incoming_supply(opponent_farm, board_size, day, cfg["opponent_lookahead_days"])
            market_orders = _market_orders(farm, private, info, cfg, prices, day, opponent_supply)
            farmer_action, hands_actions = _plan_units(
                farm, private, board_size, day, info, cfg, prices, state["unit_targets"]
            )

            return {{"farmer": farmer_action, "hands": hands_actions, "market": market_orders}}
        except Exception as exc:  # noqa: BLE001 -- deliberate catch-all safety net
            print(f"kaggriculture submission: swallowed exception, falling back to PASS: {{exc!r}}", file=sys.stderr)
            return dict(SAFE_FALLBACK)

    return agent


agent = make_agent(CONFIG)
'''
    OUT_PATH.write_text(out)
    print(f"Wrote {OUT_PATH} ({len(out)} bytes)")


if __name__ == "__main__":
    build()
